### ISSUE TITLE
How translate the CMS ?

### ISSUE THREAD

**Issue by Anthologique** [sant0ro/habbo-web-cms#8]
Hello, i am french user, and i will translate Habbo Web CMS.
How folder translate please ?

**Comment by sant0ro** [comment]
Hello you can translate the file /web/Public/web-img/lang/fr.json (creating fr.json)

Here is the Habbo.fr French Language file: https://habboo-a.akamaihd.net/habbo-web-l10n/fr.json

Only download it. And put in /web/Public/web-img/lang/

After that open web/Public/web-img/js/SiteApi.js and change en-us or en to fr.

Remember maybe some things in these language pack are incompatible, since the HabboWEB version in AzureWEB is from February/January 2016.

**Comment by Anthologique** [comment]
Ok, perfect, can you update the HabboWEB version please ? :)

**Comment by sant0ro** [comment]
No. only in future.
